[project]
name = "thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cdlg-package",
    "matplotlib>=3.10",
    "minisom>=2.3.1",
    "notebook>=7.5",
    "numpy>=1.26",
    "pandas>=2.0",
    "plotly>=5.20",
    "pm4py>=2.7",
    "rheon",
    "scikit-learn>=1.4",
    "seaborn>=0.13",
    "streamlit>=1.35",
    "tabulate>=0.9",
]

[tool.uv.sources]
cdlg-package = { path = "cdlg-package", editable = true }
rheon = { path = "../rheon", editable = true }

[dependency-groups]
dev = [
    "hypothesis>=6.148.0",
    "pytest>=9.0.0",
]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
